Repository vbe0201/kobold, pull requests merged in 2022-10, with the labels that each got.

#1 Implement parser for BCD format
  Cargo.lock
  kobold/Cargo.toml
  kobold/src/formats/bcd.rs
  kobold/src/formats/mod.rs
  kobold/src/formats/utils.rs
  kobold/src/lib.rs
Labels: Hacktoberfest

#2 Implement parsers for nav formats
  Cargo.lock
  kobold/Cargo.toml
  kobold/src/formats/mod.rs
  kobold/src/formats/nav.rs
  kobold/src/formats/utils.rs
Labels: hacktoberfest-accepted

#3 Implement parser for the POI format
  kobold/src/formats/mod.rs
  kobold/src/formats/poi.rs
  kobold/src/formats/utils.rs
Labels: hacktoberfest-accepted

#4 Implement parser for KIWAD archives
  kobold/src/formats/mod.rs
  kobold/src/formats/wad.rs
  kobold/src/main.rs
Labels: hacktoberfest-accepted

#6 update TypeList to use v2json
  README.md
  kobold/src/object_property/type_list.rs
  kobold/src/object_property/type_tag.rs
Labels: documentation, enhancement
